#!/usr/bin/env python3
"""build-proposal-pdf.py — docs/33 Phase 4 (§4.8 Proposal Draft).

Generates a Good/Better/Best proposal draft PDF for one estimate run.
Client-facing scope only: option totals and included scope, never internal
costs, margins, or vendor pricing. Every §4.8 acknowledgment gets an
initials block; the last page carries the full signature block.

DRAFT discipline (docs/33 §3): the PDF is watermarked DRAFT and footers say
"not for client delivery until approved". Removing the watermark is part of
the human approval flow, never this script.

Usage:
  python3 scripts/build-proposal-pdf.py --input run.json --out proposal.pdf

Input JSON shape:
{
  "address": "...", "prepared_for": "...", "date": "YYYY-MM-DD",
  "company": {"name": "...", "phone": "...", "website": "..."},
  "measurements": {"squares": .., "waste_adjusted_squares": .., "predominant_pitch": "..",
                   "eaves_lf": .., "ridges_lf": .., "valleys_lf": .., "facet_count": ..,
                   "low_slope_area_sqft": .., "stories": ..},
  "options": [{"tier_label": "Good", "name": "...", "shingle_line": "...",
               "total_price": .., "scope": ["...", ...], "warranty": "...",
               "labor_warranty": "..."}],
  "deposit_pct": 30, "decking_allowance_sheets": 2, "decking_change_order_price": 45,
  "notes": ["..."]
}
"""

import argparse, json
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (BaseDocTemplate, PageTemplate, Frame, Paragraph,
                                Spacer, Table, TableStyle, PageBreak)

NAVY = colors.HexColor('#1b2a41')
ACCENT = colors.HexColor('#c8102e')
GREY = colors.HexColor('#5b6770')
LIGHT = colors.HexColor('#f2f4f7')


def initials_row(label):
    t = Table([[Paragraph(label, STYLES['ack']), 'Initials: ______']],
              colWidths=[5.4 * inch, 1.6 * inch])
    t.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTNAME', (1, 0), (1, 0), 'Helvetica'),
        ('FONTSIZE', (1, 0), (1, 0), 9),
        ('TEXTCOLOR', (1, 0), (1, 0), GREY),
        ('LINEBELOW', (0, 0), (-1, 0), 0.4, colors.HexColor('#d8dce1')),
        ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    return t


def watermark_and_footer(canvas, doc):
    canvas.saveState()
    # DRAFT watermark
    canvas.setFont('Helvetica-Bold', 64)
    canvas.setFillColor(colors.Color(0.86, 0.88, 0.91, alpha=0.45))
    canvas.translate(4.25 * inch, 5.5 * inch)
    canvas.rotate(38)
    canvas.drawCentredString(0, 0, 'DRAFT — PENDING APPROVAL')
    canvas.restoreState()
    canvas.saveState()
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(GREY)
    canvas.drawString(0.75 * inch, 0.5 * inch,
                      'DRAFT — generated by Open Brain estimating; not for client delivery until approved (docs/33 §3.1).')
    canvas.drawRightString(7.75 * inch, 0.5 * inch, f'Page {doc.page}')
    canvas.restoreState()


def build(data, out_path):
    doc = BaseDocTemplate(out_path, pagesize=letter,
                          leftMargin=0.75 * inch, rightMargin=0.75 * inch,
                          topMargin=0.7 * inch, bottomMargin=0.8 * inch,
                          title=f"Roof Replacement Proposal (DRAFT) — {data['address']}",
                          author=data['company']['name'])
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='main')
    doc.addPageTemplates([PageTemplate(id='all', frames=[frame], onPage=watermark_and_footer)])
    s = STYLES
    story = []

    # ── Cover / header ──
    story.append(Paragraph(data['company']['name'], s['co']))
    story.append(Paragraph('Residential Reroof Proposal', s['title']))
    story.append(Paragraph(f"<b>Property:</b> {data['address']}", s['meta']))
    story.append(Paragraph(f"<b>Prepared for:</b> {data.get('prepared_for') or 'Homeowner'}"
                           f" &nbsp;&nbsp; <b>Date:</b> {data['date']}"
                           f" &nbsp;&nbsp; <b>Valid:</b> 30 days", s['meta']))
    story.append(Spacer(1, 10))

    # ── Roof summary ──
    m = data['measurements']
    story.append(Paragraph('Your Roof', s['h2']))
    rows = [['Roof size', f"{m['squares']} squares ({int(m['squares'] * 100)} sqft)"],
            ['With recommended waste', f"{m['waste_adjusted_squares']} squares"],
            ['Predominant pitch', m['predominant_pitch']],
            ['Facets', str(int(m['facet_count']))],
            ['Eaves / Ridges / Valleys', f"{m['eaves_lf']} lf / {m['ridges_lf']} lf / {m['valleys_lf']} lf"],
            ['Stories', str(int(m['stories']))]]
    if m.get('low_slope_area_sqft'):
        rows.append(['Low-slope area', f"{int(m['low_slope_area_sqft'])} sqft (self-adhered membrane system)"])
    t = Table(rows, colWidths=[2.4 * inch, 4.6 * inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'), ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (0, -1), NAVY), ('ROWBACKGROUNDS', (0, 0), (-1, -1), [LIGHT, colors.white]),
        ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    # ── Options side-by-side ──
    story.append(Paragraph('Your Options', s['h2']))
    opts = data['options']
    hdr = [Paragraph(f"<b>{o['tier_label']}</b><br/><font size=8>{o['shingle_line']}</font>", s['opt_h']) for o in opts]
    price = [Paragraph(f"<b>${o['total_price']:,.0f}</b>", s['opt_p']) for o in opts]
    warr = [Paragraph(f"{o['warranty']}<br/><font size=7.5 color='#5b6770'>{o['labor_warranty']}</font>", s['opt_c']) for o in opts]
    maxs = max(len(o['scope']) for o in opts)
    scope_rows = []
    for i in range(maxs):
        scope_rows.append([Paragraph(o['scope'][i], s['opt_c']) if i < len(o['scope']) else '' for o in opts])
    grid = [hdr, price] + scope_rows + [warr]
    w = (7.0 / len(opts)) * inch
    ot = Table(grid, colWidths=[w] * len(opts), repeatRows=2)
    ot.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), NAVY), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (-1, 1), LIGHT),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#d8dce1')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(ot)
    story.append(Spacer(1, 8))
    story.append(Paragraph('All options include: tear-off and disposal, synthetic underlayment, ice &amp; water '
                           'protection at valleys, starter strip, drip edge and gutter apron, new pipe flashings, '
                           'ridge ventilation as specified, nails and fasteners, full magnetic sweep and cleanup, '
                           'permit handling, and delivery.', s['fine']))
    story.append(Spacer(1, 6))
    story.append(initials_row('I have reviewed the options above and my SELECTED PACKAGE is: '
                              '&nbsp; ☐ Good &nbsp; ☐ Better &nbsp; ☐ Best'))
    story.append(initials_row('I acknowledge the TOTAL PRICE of my selected option.'))
    story.append(PageBreak())

    # ── Selections, payment, allowances ──
    story.append(Paragraph('Color &amp; Material Selections', s['h2']))
    story.append(Paragraph('Shingle color: ______________________ &nbsp;&nbsp; Drip edge color: ______________________ '
                           '&nbsp;&nbsp; Vent color: ______________________', s['body']))
    story.append(initials_row('My color and material selections above are correct.'))
    story.append(Spacer(1, 10))

    story.append(Paragraph('Payment Terms', s['h2']))
    story.append(Paragraph(
        f"A deposit of {data['deposit_pct']}% of the selected option total is due at signing; the balance is due on "
        f"completion. We accept check, ACH, and major cards. Financing available on approved credit. "
        f"<i>(Deposit percentage pending final company policy confirmation.)</i>", s['body']))
    story.append(initials_row('I acknowledge the payment and deposit terms.'))
    story.append(Spacer(1, 10))

    story.append(Paragraph('Decking Allowance &amp; Change Orders', s['h2']))
    story.append(Paragraph(
        f"This proposal includes replacement of up to <b>{data['decking_allowance_sheets']} sheets</b> of roof decking "
        f"(7/16\" OSB) if rot or damage is found. Additional sheets, if required, are a change order at "
        f"<b>${data['decking_change_order_price']:.0f} per sheet</b>, approved by you before installation.", s['body']))
    story.append(initials_row('I acknowledge the decking allowance and per-sheet change-order price.'))
    story.append(Spacer(1, 10))

    story.append(Paragraph('Right to Cancel', s['h2']))
    story.append(Paragraph(
        'You may cancel this agreement without penalty within three (3) business days of signing, in accordance with '
        'applicable federal and state law. If your project involves an insurance claim, additional state-specific '
        'cancellation rights may apply.', s['body']))
    story.append(initials_row('I acknowledge my right to cancel.'))
    story.append(Spacer(1, 10))

    story.append(Paragraph('Terms &amp; Conditions (Summary)', s['h2']))
    for n in data.get('notes', []):
        story.append(Paragraph(f'• {n}', s['fine']))
    story.append(Paragraph('• Workmanship and manufacturer warranties are as listed per option above; warranty '
                           'registration is completed on final payment.', s['fine']))
    story.append(Paragraph('• Pricing is valid for 30 days and subject to material availability.', s['fine']))
    story.append(Paragraph('• Full terms and conditions are provided with the final contract packet. '
                           '<i>(Standard T&amp;C packet pending company legal review — placeholder.)</i>', s['fine']))
    story.append(initials_row('I have read the terms and conditions summary.'))
    story.append(Spacer(1, 18))

    # ── Signature block ──
    story.append(Paragraph('Acceptance', s['h2']))
    sig = Table([
        ['Homeowner signature:', '_______________________________', 'Date:', '______________'],
        ['Printed name:', '_______________________________', '', ''],
        [f"{data['company']['name']} representative:", '_______________________________', 'Date:', '______________'],
    ], colWidths=[2.1 * inch, 2.9 * inch, 0.6 * inch, 1.4 * inch])
    sig.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 9), ('TEXTCOLOR', (0, 0), (0, -1), NAVY),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(sig)
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"{data['company']['name']} • {data['company']['phone']} • {data['company']['website']}", s['fine']))

    doc.build(story)


STYLES = None

def make_styles():
    base = getSampleStyleSheet()
    return {
        'co': ParagraphStyle('co', parent=base['Normal'], fontName='Helvetica-Bold', fontSize=11, textColor=ACCENT, spaceAfter=2),
        'title': ParagraphStyle('title', parent=base['Title'], fontName='Helvetica-Bold', fontSize=22, textColor=NAVY, alignment=0, spaceAfter=6),
        'meta': ParagraphStyle('meta', parent=base['Normal'], fontSize=9.5, textColor=GREY, spaceAfter=2),
        'h2': ParagraphStyle('h2', parent=base['Heading2'], fontName='Helvetica-Bold', fontSize=12.5, textColor=NAVY, spaceBefore=4, spaceAfter=5),
        'body': ParagraphStyle('body', parent=base['Normal'], fontSize=9.5, leading=13),
        'fine': ParagraphStyle('fine', parent=base['Normal'], fontSize=8, leading=11, textColor=GREY),
        'ack': ParagraphStyle('ack', parent=base['Normal'], fontSize=9, leading=12, textColor=NAVY),
        'opt_h': ParagraphStyle('opt_h', parent=base['Normal'], fontSize=10, leading=12, textColor=colors.white),
        'opt_p': ParagraphStyle('opt_p', parent=base['Normal'], fontSize=14, leading=16, textColor=NAVY),
        'opt_c': ParagraphStyle('opt_c', parent=base['Normal'], fontSize=8.5, leading=11),
    }


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--input', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    STYLES = make_styles()
    with open(a.input) as f:
        build(json.load(f), a.out)
    print(f'wrote {a.out}')
