-- 215-friday-wip-ar-master.sql
-- Friday WIP/AR live board (docs/85) — the Supabase master behind the
-- Command Center "Friday WIP/AR" tab and the Thursday AR/WIP pack.
--
-- One row per job in the open-balance ledger (the population of sheet
-- 11_Friday_Meeting in AR_WIP_Pack v4, credit balances included per
-- 0_EXCEPTIONS check 18). Computed columns are rebuilt nightly by
-- refresh_wip_ar_master() from the AccuLynx mirror; the meeting-editable
-- columns (expected dates, collected?, notes) are NEVER touched by the
-- refresh. Weekly roll (Thursday) moves this week's expected-paid date
-- into "prior" and scores HIT/MISS.
--
-- CPA accrual additions (2026-08-05 request):
--   * costs_incurred_to_date — from QBO bills/purchases whose line
--     CustomerRef sub-customer name ends in the PE job number (":MC-68").
--   * est_total_costs — placeholder until the AccuLynx worksheet DETAIL
--     endpoint (line-level costs) is mirrored; worksheetSectionTotals in
--     acculynx_job_financials.raw is price-side only.
--   * wip_accrual_snapshot(p_cutoff) — billed-to-date and costs-to-date
--     with a date cutoff for earned-revenue (% completion) calcs.
--
-- Additive + idempotent. No destructive SQL. RLS: service_role only.

-- ---------------------------------------------------------------------------
-- 1. Master table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wip_ar_master (
  acculynx_job_id  text PRIMARY KEY,

  -- computed nightly (do not hand-edit; refresh overwrites)
  location          text,             -- acculynx_jobs.account_key
  job_number        text,             -- crm_pipeline.client_job_number (MC-68 …)
  client            text,
  job_name          text,
  milestone         text,             -- raw AccuLynx milestone
  bucket            text,             -- locked dashboard bucket (docs/75 / PEC-100)
  salesperson       text,
  category          text,
  collection_status text,             -- Pending | Invoiced | Critical AR | Collected in Full
  contract_amount   numeric(14,2) DEFAULT 0,  -- L: job_financials.approved_job_value
  outstanding_ar    numeric(14,2) DEFAULT 0,  -- N: job_financials.balance_due
  billed_total      numeric(14,2) DEFAULT 0,  -- P: Σ invoices.total_price (non-void)
  billed_ar         numeric(14,2) DEFAULT 0,  -- Q: Σ invoices.balance_due (non-void)
  unbilled          numeric(14,2) DEFAULT 0,  -- N − Q
  collected_revenue numeric(14,2) DEFAULT 0,  -- R: P − Q
  invoice_count     integer       DEFAULT 0,
  change_order_total numeric(14,2),           -- worksheetSectionTotals.changeOrderTotal (price side)
  action            text,             -- COLLECT | INVOICE FIRST | Collect + invoice rest | -
  acculynx_url      text,
  has_insurance     boolean DEFAULT false,

  -- CPA accrual (computed)
  est_total_costs        numeric(14,2),  -- NULL until worksheet-detail mirror lands (docs/85 §gap)
  est_costs_source       text,           -- e.g. 'acculynx_worksheet_detail' when wired
  costs_incurred_to_date numeric(14,2),  -- v_qbo_job_costs at refresh cutoff
  costs_incurred_asof    date,

  -- meeting-editable (preserved across refresh)
  expected_invoice_cash_date date,     -- G on sheet 11
  expected_paid_full_date    date,     -- H on sheet 11
  prior_expected_paid_date   date,     -- I (rolled weekly)
  collected_since            text CHECK (collected_since IS NULL OR collected_since IN ('Y','N')),
  hit_miss                   text CHECK (hit_miss IS NULL OR hit_miss IN ('HIT','MISS')),
  notes                      text,

  -- bookkeeping
  in_ar_population boolean DEFAULT true,   -- false = dropped out of ledger; row kept (never delete)
  computed_at      timestamptz,
  updated_by       text,
  updated_at       timestamptz DEFAULT now(),
  created_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wip_ar_master_population
  ON wip_ar_master (in_ar_population, location, outstanding_ar DESC);
CREATE INDEX IF NOT EXISTS idx_wip_ar_master_job_number
  ON wip_ar_master (job_number);

ALTER TABLE wip_ar_master ENABLE ROW LEVEL SECURITY;  -- no policies: service_role only

-- Audit log for every human edit from the Friday board.
CREATE TABLE IF NOT EXISTS wip_ar_master_updates (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acculynx_job_id text NOT NULL,
  field           text NOT NULL,
  old_value       text,
  new_value       text,
  updated_by      text,
  updated_at      timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_wip_ar_updates_job
  ON wip_ar_master_updates (acculynx_job_id, updated_at DESC);
ALTER TABLE wip_ar_master_updates ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 2. QBO job-cost views (CPA: costs incurred to date, date-cutoff capable)
--    Bill/purchase expense lines carry CustomerRef sub-customer names that
--    end in the PE job number ("Shores, Ridge & (342):MC-68"). Parse the
--    trailing segment and join to the job ledger via job_number.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_qbo_job_cost_lines AS
WITH bill_lines AS (
  SELECT
    'bill'::text                         AS source,
    b.qbo_id                             AS qbo_txn_id,
    b.txn_date::date                     AS txn_date,
    b.vendor_name                        AS vendor_name,
    1::numeric                           AS sign,
    l.value                              AS line
  FROM qbo_bills b
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(b.lines, b.raw -> 'Line')) AS l(value)
), purchase_lines AS (
  SELECT
    'purchase'::text                     AS source,
    p.qbo_id                             AS qbo_txn_id,
    p.txn_date::date                     AS txn_date,
    p.entity_name                        AS vendor_name,
    CASE WHEN coalesce(p.credit, false) THEN -1 ELSE 1 END::numeric AS sign,
    l.value                              AS line
  FROM qbo_purchases p
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(p.lines, p.raw -> 'Line')) AS l(value)
), all_lines AS (
  SELECT * FROM bill_lines
  UNION ALL
  SELECT * FROM purchase_lines
)
SELECT
  source,
  qbo_txn_id,
  txn_date,
  vendor_name,
  COALESCE(
    line -> 'AccountBasedExpenseLineDetail' -> 'CustomerRef' ->> 'name',
    line -> 'ItemBasedExpenseLineDetail'    -> 'CustomerRef' ->> 'name'
  )                                                        AS customer_ref_name,
  NULLIF(TRIM(substring(
    COALESCE(
      line -> 'AccountBasedExpenseLineDetail' -> 'CustomerRef' ->> 'name',
      line -> 'ItemBasedExpenseLineDetail'    -> 'CustomerRef' ->> 'name'
    ) FROM ':([^:]+)$'
  )), '')                                                  AS job_number,
  COALESCE(
    line -> 'AccountBasedExpenseLineDetail' -> 'AccountRef' ->> 'name',
    line -> 'ItemBasedExpenseLineDetail'    -> 'ItemRef'    ->> 'name'
  )                                                        AS account_or_item,
  sign * (line ->> 'Amount')::numeric                      AS amount
FROM all_lines
WHERE COALESCE(
        line -> 'AccountBasedExpenseLineDetail' -> 'CustomerRef' ->> 'name',
        line -> 'ItemBasedExpenseLineDetail'    -> 'CustomerRef' ->> 'name'
      ) IS NOT NULL
  AND (line ->> 'Amount') IS NOT NULL;

CREATE OR REPLACE VIEW v_qbo_job_costs AS
SELECT
  job_number,
  round(sum(amount), 2)  AS costs_incurred,
  count(*)               AS cost_lines,
  min(txn_date)          AS first_cost_date,
  max(txn_date)          AS last_cost_date
FROM v_qbo_job_cost_lines
WHERE job_number IS NOT NULL
GROUP BY job_number;

-- ---------------------------------------------------------------------------
-- 3. Nightly refresh — rebuild computed columns, preserve human edits.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION refresh_wip_ar_master(p_asof date DEFAULT current_date)
RETURNS TABLE (jobs_upserted integer, jobs_dropped integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_upserted    integer := 0;
  v_dropped     integer := 0;
  v_run_started timestamptz := clock_timestamp();
BEGIN
  WITH pipeline AS (
    -- dedupe crm_pipeline: prefer api_sync over csv_initial (build_pack.py parity)
    SELECT DISTINCT ON (acculynx_job_id) *
    FROM crm_pipeline
    WHERE acculynx_job_id IS NOT NULL
    ORDER BY acculynx_job_id, (data_source = 'api_sync') DESC
  ), inv AS (
    SELECT job_id,
           round(sum(total_price::numeric), 2)  AS billed_total,
           round(sum(balance_due::numeric), 2)  AS billed_ar,
           count(*)                             AS invoice_count
    FROM acculynx_invoices
    WHERE job_id IS NOT NULL
      AND lower(coalesce(current_invoice_state, '')) <> 'void'
    GROUP BY job_id
  ), base AS (
    SELECT
      p.acculynx_job_id                                   AS jid,
      coalesce(aj.account_key, 'unknown')                 AS location,
      coalesce(p.client_job_number, '')                   AS job_number,
      coalesce(p.client_name, p.job_name, '')             AS client,
      coalesce(p.job_name, '')                            AS job_name,
      lower(trim(coalesce(p.current_milestone, '')))      AS milestone,
      coalesce(p.primary_salesperson, '(unassigned)')     AS salesperson,
      coalesce(aj.job_category_name, '')                  AS category,
      coalesce(
        (f.raw -> 'worksheetSectionTotals' ->> 'changeOrderTotal')::numeric,
        f.change_order_total::numeric)                    AS change_order_total,
      coalesce(f.approved_job_value::numeric,
               p.contract_amount::numeric, 0)             AS contract_amount,
      coalesce(f.balance_due::numeric,
               p.balance_due::numeric, 0)                 AS outstanding_ar,
      coalesce(i.billed_total, 0)                         AS billed_total,
      coalesce(i.billed_ar, 0)                            AS billed_ar,
      coalesce(i.invoice_count, 0)                        AS invoice_count,
      (coalesce(i.invoice_count, 0) > 0
        OR coalesce(i.billed_total, 0) > 0)               AS has_invoice,
      (coalesce(p.insurance_company, '') <> ''
        OR coalesce(p.insurance_claim_number, '') <> '')  AS has_insurance
    FROM pipeline p
    LEFT JOIN acculynx_jobs aj          ON aj.id = p.acculynx_job_id
    LEFT JOIN acculynx_job_financials f ON f.job_id = p.acculynx_job_id
    LEFT JOIN inv i                     ON i.job_id = p.acculynx_job_id
    WHERE lower(trim(coalesce(p.current_milestone, '')))
          NOT IN ('cancelled', 'dead', 'unknown')
  ), classified AS (
    SELECT b.*,
      -- locked dashboard bucket (dashboard_bucket() parity, docs/75)
      CASE
        WHEN b.milestone IN ('unassigned_lead','assigned_lead','lead') THEN 'Lead'
        WHEN b.milestone = 'prospect' THEN 'Estimating'
        WHEN b.milestone = 'closed' AND b.outstanding_ar > 0 THEN 'Closed w/AR'
        WHEN b.milestone = 'closed' THEN 'Closed'
        WHEN b.milestone = 'invoiced' AND b.has_insurance AND b.outstanding_ar > 0
          THEN 'Approved – deposit collected → WIP'
        WHEN b.milestone = 'invoiced' THEN 'Invoiced'
        WHEN b.milestone = 'completed' THEN 'Approved – work complete → final sign-off'
        WHEN b.milestone = 'approved' AND b.has_invoice AND b.outstanding_ar > 0
          THEN 'Approved – deposit invoiced'
        WHEN b.milestone = 'approved' AND b.has_invoice
          THEN 'Approved – deposit collected → WIP'
        WHEN b.milestone = 'approved' THEN 'Contracted – awaiting deposit'
        ELSE 'Estimating'
      END AS bucket
    FROM base b
  ), scored AS (
    SELECT c.*,
      round(c.billed_total - c.billed_ar, 2)   AS collected_revenue,
      round(c.outstanding_ar - c.billed_ar, 2) AS unbilled,
      -- collection_status() parity (column S traffic light)
      CASE
        WHEN c.contract_amount > 0
         AND (c.billed_total - c.billed_ar) + 0.005 >= c.contract_amount
          THEN 'Collected in Full'
        WHEN c.bucket IN ('Lead','Estimating') THEN 'Pending'
        WHEN c.bucket IN ('Contracted – awaiting deposit',
                          'Approved – deposit invoiced',
                          'Approved – deposit collected → WIP') THEN 'Invoiced'
        WHEN c.outstanding_ar > 0 THEN 'Critical AR'
        ELSE 'Pending'
      END AS collection_status,
      CASE
        WHEN c.billed_ar > 0 AND (c.outstanding_ar - c.billed_ar) > 0
          THEN 'Collect + invoice rest'
        WHEN c.billed_ar > 0 THEN 'COLLECT'
        WHEN (c.outstanding_ar - c.billed_ar) > 0 THEN 'INVOICE FIRST'
        ELSE '-'
      END AS action
    FROM classified c
  ), ledger AS (
    -- Friday board population: any open balance, credit balances included
    -- (0_EXCEPTIONS check 18: build on the ledger, not N>0). Closed-clean out.
    SELECT s.* FROM scored s
    WHERE (abs(s.outstanding_ar) > 0.004 OR abs(s.billed_ar) > 0.004)
      AND NOT (s.milestone = 'closed' AND s.outstanding_ar <= 0)
  ), up AS (
    INSERT INTO wip_ar_master AS m (
      acculynx_job_id, location, job_number, client, job_name, milestone,
      bucket, salesperson, category, collection_status, contract_amount,
      outstanding_ar, billed_total, billed_ar, unbilled, collected_revenue,
      invoice_count, change_order_total, action, acculynx_url, has_insurance,
      costs_incurred_to_date, costs_incurred_asof,
      in_ar_population, computed_at
    )
    SELECT
      l.jid, l.location, l.job_number, l.client, l.job_name, l.milestone,
      l.bucket, l.salesperson, l.category, l.collection_status, l.contract_amount,
      l.outstanding_ar, l.billed_total, l.billed_ar, l.unbilled, l.collected_revenue,
      l.invoice_count, l.change_order_total, l.action,
      'https://my.acculynx.com/jobs/' || l.jid, l.has_insurance,
      qc.costs_incurred, CASE WHEN qc.costs_incurred IS NOT NULL THEN p_asof END,
      true, v_run_started
    FROM ledger l
    LEFT JOIN v_qbo_job_costs qc
      ON qc.job_number = l.job_number AND l.job_number <> ''
    ON CONFLICT (acculynx_job_id) DO UPDATE SET
      location = EXCLUDED.location,
      job_number = EXCLUDED.job_number,
      client = EXCLUDED.client,
      job_name = EXCLUDED.job_name,
      milestone = EXCLUDED.milestone,
      bucket = EXCLUDED.bucket,
      salesperson = EXCLUDED.salesperson,
      category = EXCLUDED.category,
      collection_status = EXCLUDED.collection_status,
      contract_amount = EXCLUDED.contract_amount,
      outstanding_ar = EXCLUDED.outstanding_ar,
      billed_total = EXCLUDED.billed_total,
      billed_ar = EXCLUDED.billed_ar,
      unbilled = EXCLUDED.unbilled,
      collected_revenue = EXCLUDED.collected_revenue,
      invoice_count = EXCLUDED.invoice_count,
      change_order_total = EXCLUDED.change_order_total,
      action = EXCLUDED.action,
      acculynx_url = EXCLUDED.acculynx_url,
      has_insurance = EXCLUDED.has_insurance,
      costs_incurred_to_date = EXCLUDED.costs_incurred_to_date,
      costs_incurred_asof = EXCLUDED.costs_incurred_asof,
      in_ar_population = true,
      computed_at = EXCLUDED.computed_at
    RETURNING 1
  )
  SELECT count(*) INTO v_upserted FROM up;

  -- Jobs that left the ledger: keep the row (never delete), flag it out.
  -- Anything this run's upsert did not touch has computed_at < v_run_started.
  UPDATE wip_ar_master m
  SET in_ar_population = false
  WHERE m.in_ar_population
    AND (m.computed_at IS NULL OR m.computed_at < v_run_started);
  GET DIAGNOSTICS v_dropped = ROW_COUNT;

  RETURN QUERY SELECT v_upserted, v_dropped;
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. Weekly roll (Thursday, before the pack builds): score HIT/MISS from
--    last week's expected-paid date, then roll this week's date to prior.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION roll_wip_ar_week()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rolled integer := 0;
BEGIN
  UPDATE wip_ar_master
  SET hit_miss = CASE
        WHEN prior_expected_paid_date IS NULL THEN NULL
        WHEN collected_since = 'Y' THEN 'HIT'
        WHEN prior_expected_paid_date < current_date
             AND coalesce(collected_since, 'N') = 'N' THEN 'MISS'
        ELSE NULL
      END
  WHERE in_ar_population;

  UPDATE wip_ar_master
  SET prior_expected_paid_date = expected_paid_full_date,
      collected_since = NULL
  WHERE in_ar_population
    AND expected_paid_full_date IS NOT NULL;
  GET DIAGNOSTICS v_rolled = ROW_COUNT;
  RETURN v_rolled;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. CPA accrual snapshot — billed-to-date and costs-to-date at a cutoff.
--    Earned revenue (% completion) = est margin applied to cost progress;
--    the CPA runs the method, we hand them the four cutoff inputs.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wip_accrual_snapshot(p_cutoff date DEFAULT current_date)
RETURNS TABLE (
  acculynx_job_id text,
  job_number text,
  client text,
  location text,
  bucket text,
  contract_amount numeric,
  change_order_total numeric,
  est_total_costs numeric,
  billed_to_cutoff numeric,
  billed_ar_current numeric,
  costs_incurred_to_cutoff numeric,
  cutoff date
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  -- Single-pass aggregates (215c): the correlated-subquery version expanded
  -- the QBO jsonb per job and hit statement timeout.
  WITH inv AS (
    SELECT i.job_id,
           round(sum(i.total_price::numeric), 2) AS billed_to_cutoff
    FROM acculynx_invoices i
    WHERE lower(coalesce(i.current_invoice_state, '')) <> 'void'
      AND coalesce(i.invoice_date::date, i.created_date::date) <= p_cutoff
    GROUP BY i.job_id
  ), costs AS (
    SELECT cl.job_number,
           round(sum(cl.amount), 2) AS costs_to_cutoff
    FROM v_qbo_job_cost_lines cl
    WHERE cl.job_number IS NOT NULL
      AND cl.txn_date <= p_cutoff
    GROUP BY cl.job_number
  )
  SELECT
    m.acculynx_job_id,
    m.job_number,
    m.client,
    m.location,
    m.bucket,
    m.contract_amount,
    m.change_order_total,
    m.est_total_costs,
    coalesce(inv.billed_to_cutoff, 0)  AS billed_to_cutoff,
    m.billed_ar                        AS billed_ar_current,
    coalesce(costs.costs_to_cutoff, 0) AS costs_incurred_to_cutoff,
    p_cutoff                           AS cutoff
  FROM wip_ar_master m
  LEFT JOIN inv   ON inv.job_id = m.acculynx_job_id
  LEFT JOIN costs ON costs.job_number = m.job_number AND m.job_number <> ''
  WHERE m.in_ar_population
$$;

-- ---------------------------------------------------------------------------
-- 6. Schedules (pg_cron). Nightly refresh 10:45 UTC (04:45/05:45 CT), after
--    the 03:30 ET ABC sync and the hourly AccuLynx sync. Thursday roll at
--    10:30 UTC so HIT/MISS is scored before the 11:00 UTC pack build.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('wip-ar-master-nightly')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'wip-ar-master-nightly');
    PERFORM cron.schedule(
      'wip-ar-master-nightly',
      '45 10 * * *',
      $cron$SELECT refresh_wip_ar_master();$cron$
    );

    PERFORM cron.unschedule('wip-ar-week-roll-thursday')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'wip-ar-week-roll-thursday');
    PERFORM cron.schedule(
      'wip-ar-week-roll-thursday',
      '30 10 * * 4',
      $cron$SELECT roll_wip_ar_week();$cron$
    );
  END IF;
END $$;
