-- 224-agent-fix-approvals.sql
-- Maya diagnose → Slack-approved repair (A3: proposals/a3-maya-diagnose-repair-slack-gate.md).
--
-- agent_fix_approvals is the FAIL-CLOSED gate: the executor may only run a plan
-- when a row exists with status='approved' AND the approver's Slack user ID is
-- on the allowlist AND the stored plan_hash equals the hash of the plan it is
-- about to execute. A changed plan re-requires approval. Decisions (Chris,
-- 2026-08-07): channel #pe-cc-dev-team (C0BNVF99Y74); approver allowlist =
-- U0B8SGJJZLJ (Chris/admin) only; proposals expire after 7 days; Phase A
-- (read-only diagnosis) auto-runs on every [MAYA] accounting intake.
--
-- ob_readonly is the diagnosis role: SELECT-only, so Phase A physically
-- cannot write. Created NOLOGIN here; the host installer grants LOGIN with a
-- host-local password (never committed).
--
-- Additive + idempotent. RLS: service_role only.

CREATE TABLE IF NOT EXISTS agent_fix_approvals (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_identifier    text NOT NULL,               -- e.g. 'PEC-186'
  plan_type           text NOT NULL,               -- whitelist: 'mirror_refresh' (pilot)
  plan                jsonb NOT NULL,              -- canonical plan parameters
  plan_hash           text NOT NULL,               -- sha256 of canonical plan JSON
  proposal_text       text,                        -- what was posted to Slack
  proposal_slack_ts   text,                        -- Slack ts of the proposal message
  channel_id          text NOT NULL DEFAULT 'C0BNVF99Y74',
  status              text NOT NULL DEFAULT 'proposed'
                      CHECK (status IN ('proposed','approved','rejected','expired','executed','failed')),
  proposed_at         timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz NOT NULL DEFAULT now() + interval '7 days',
  approved_by_slack_id text,
  approval_slack_ts   text,                        -- evidence: ts of the APPROVE/REJECT message
  decided_at          timestamptz,
  executed_at         timestamptz,
  execution_note      text,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_fix_approvals_issue_plan
  ON agent_fix_approvals (issue_identifier, plan_hash);
CREATE INDEX IF NOT EXISTS idx_agent_fix_approvals_status
  ON agent_fix_approvals (status, expires_at);

ALTER TABLE agent_fix_approvals ENABLE ROW LEVEL SECURITY;  -- no policies: service_role only

-- Diagnosis role: SELECT-only over public. LOGIN + password granted host-side.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ob_readonly') THEN
    CREATE ROLE ob_readonly NOLOGIN;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO ob_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ob_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ob_readonly;

-- ---------------------------------------------------------------------------
-- 224b: maya_gate_cursor_jump — the ONLY cursor mutation the gate's
-- mirror_refresh executor performs (besides trigger_acculynx_sync and
-- refresh_wip_ar_master). Parks the account's job-walk cursor on the job
-- immediately BEFORE the target (created_date order) so the next sync run
-- re-evaluates it under D-16. Self-healing regardless (wrap fix, PEC-187).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION maya_gate_cursor_jump(p_account_key text, p_job_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_prev text;
  v_pos  integer;
BEGIN
  WITH ordered AS (
    SELECT id, row_number() OVER (ORDER BY created_date ASC, id ASC) AS rn
    FROM acculynx_jobs WHERE account_key = p_account_key
  )
  SELECT o_prev.id, o_tgt.rn INTO v_prev, v_pos
  FROM ordered o_tgt
  LEFT JOIN ordered o_prev ON o_prev.rn = o_tgt.rn - 1
  WHERE o_tgt.id = p_job_id;

  IF v_pos IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'job not found in account');
  END IF;

  UPDATE acculynx_sync_watermark
  SET last_walked_job_id = v_prev, updated_at = now()
  WHERE account_key = p_account_key AND resource_type = 'job_walk';

  RETURN jsonb_build_object('ok', true, 'account', p_account_key, 'target_pos', v_pos, 'cursor_set_to', v_prev);
END;
$$;
