/** Isolated local browser proof. Run from CRM root; never connects to a provider. */
import {createServer} from 'vite';
import {chromium} from 'playwright';
import {build} from 'esbuild';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=process.cwd();
const app=path.join(root,'artifacts/companion/brain-design/app/command-center');
const installed=process.env.CC_WIP_TEST_APP||app;
const library='/private/tmp/cc-wip-browser-library/index.mjs';
await build({entryPoints:[path.join(installed,'node_modules/@proexteriors/sales-workspace/dist/index.js')],bundle:true,format:'esm',platform:'browser',external:['react','react/jsx-runtime','react/jsx-dev-runtime'],outfile:library,logLevel:'silent'});
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import DesktopSales from '${app}/src/components/sales/SalesWorkspace.tsx';import '${app}/node_modules/@proexteriors/design-system/tokens.css';window.root=createRoot(document.getElementById('app'));window.root.render(React.createElement(DesktopSales,{initialRoute:{page:'Pipeline'}}));`;
const facade=`import React from 'react';import {WeeklyWorkspace as ActualWeekly,createSalesClient} from '${library}';export {createSalesClient};export function WeeklyWorkspace(props){if(location.search.includes('guards')){window.weeklyProps=props;return React.createElement('button',{onClick:()=>props.onDirty(true)},'Edit synthetic draft');}return React.createElement(ActualWeekly,props);}`;
const server=await createServer({root,configFile:false,cacheDir:'/private/tmp/cc-wip-browser-vite-cache',esbuild:{jsx:'automatic'},optimizeDeps:{entries:[],include:['react','react-dom/client','react/jsx-runtime','react/jsx-dev-runtime']},resolve:{dedupe:['react','react-dom'],alias:[{find:'@proexteriors/sales-workspace/styles.css',replacement:path.join(installed,'node_modules/@proexteriors/sales-workspace/src/styles/scoped.css')},{find:/^@proexteriors\/sales-workspace$/,replacement:'virtual-cc-wip-facade'}]},plugins:[{name:'cc-wip-proof',configureServer(dev){dev.middlewares.use('/cc-wip-proof',async(_req,res)=>{res.setHeader('Content-Type','text/html');res.end(await dev.transformIndexHtml('/cc-wip-proof','<!doctype html><title>Local CC WIP shell proof</title><a id="host-link" href="/accounting">Accounting host link</a><form action="/auth/logout"><button>Sign out host form</button></form><div id="app"></div><script type="module" src="/@id/virtual-cc-wip-entry"></script>'));});},resolveId(id){if(['virtual-cc-wip-entry','virtual-cc-wip-facade'].includes(id))return '\0'+id;},load(id){if(id==='\0virtual-cc-wip-entry')return entry;if(id==='\0virtual-cc-wip-facade')return facade;}}],server:{host:'127.0.0.1',port:0,watch:{ignored:['**']},hmr:false,fs:{allow:[root,installed,'/private/tmp/cc-wip-browser-library']}}});

await server.listen();const browser=await chromium.launch({headless:true});const checks=[];
try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),calls=[],errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('response',r=>{if(r.status()>=400&&!r.url().includes('/api/sales/'))console.error(r.status(),r.url());});
 let sessionStatus=200,capabilities=['wip_read'];
 await page.route('**/api/sales/**',route=>{const pathname=new URL(route.request().url()).pathname;calls.push(pathname);if(pathname==='/api/sales/v1/session')return route.fulfill({status:sessionStatus,json:sessionStatus===200?{csrf_token:'synthetic',organization_id:'00000000-0000-4000-8000-000000000001',membership_id:'00000000-0000-4000-8000-000000000002',capabilities}:{message:'synthetic private exception should not be shown'}});if(pathname==='/api/sales/v1/wip-ar/cycles')return route.fulfill({json:{cycles:[],next_before:null}});return route.fulfill({status:403,json:{message:'WIP-only principal cannot use this endpoint'}});});
 const url='http://127.0.0.1:'+server.httpServer.address().port+'/cc-wip-proof';
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.getByText('No weekly cycle is available',{exact:true}).waitFor().catch(async error=>{console.error(JSON.stringify({calls,body:await page.locator('body').innerText(),scripts:await page.locator('script').evaluateAll(nodes=>nodes.map(n=>n.src))}));throw error;});assert.deepEqual(calls,['/api/sales/v1/session','/api/sales/v1/wip-ar/cycles']);checks.push('actual shared WeeklyWorkspace opens using session then weekly cycles, with no efforts/prospecting request');
 assert.equal(await page.locator('.cc-sales-wip-nav button:disabled').count(),5);checks.push('five deferred pillars are disabled');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('390px wrapper has no horizontal overflow');
 await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('320px wrapper reflows without horizontal overflow');
 sessionStatus=403;calls.length=0;await page.reload();await page.getByRole('heading',{name:'Let’s reconnect your workspace'}).waitFor();assert.deepEqual(calls,['/api/sales/v1/session']);assert.equal(await page.getByText('synthetic private exception should not be shown').count(),0);checks.push('denied session shows a safe retry state and makes no weekly request');
 sessionStatus=200;await page.getByRole('button',{name:'Check access again'}).click();await page.getByText('No weekly cycle is available',{exact:true}).waitFor();checks.push('explicit retry restores the weekly workspace after successful session verification');
 capabilities=[];calls.length=0;await page.reload();await page.getByText('Your account does not have WIP/AR access.',{exact:false}).waitFor();assert.deepEqual(calls,['/api/sales/v1/session']);checks.push('missing wip_read capability prevents child loading');
 capabilities=['wip_read'];await page.goto(url+'?guards');await page.getByRole('button',{name:'Edit synthetic draft'}).waitFor();
 const prevented=()=>page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;});
 assert.equal(await prevented(),false);await page.getByRole('button',{name:'Edit synthetic draft'}).click();assert.equal(await prevented(),true);checks.push('actual host beforeunload listener protects unsaved draft state');
 await page.evaluate(()=>{window.weeklyProps.onDirty(false);window.weeklyProps.onPending(true);});assert.equal(await prevented(),true);await page.locator('#host-link').click();assert.equal(page.url(),url+'?guards');await page.getByText('A save or upload is still in progress.',{exact:false}).waitFor();
 const formBlocked=await page.evaluate(()=>{const event=new Event('submit',{bubbles:true,cancelable:true});document.querySelector('form').dispatchEvent(event);return event.defaultPrevented;});assert.equal(formBlocked,true);checks.push('pending work blocks host navigation and logout submission');
 await page.evaluate(()=>window.weeklyProps.onPending(false));assert.equal(await prevented(),false);checks.push('guards release after confirmed completion');
 await page.evaluate(()=>window.root.unmount());assert.equal(await prevented(),false);checks.push('unmount cleans up host navigation listeners');
 assert.deepEqual(errors,[]);checks.push('no browser runtime errors');console.log(JSON.stringify({status:'PASS',checks,real_weekly_child:true,guard_callbacks_synthetic:true,hosted_acceptance:false}));
}finally{await browser.close();await server.close();}
